---
name: jsonnet
on:
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: aquaproj/aqua-installer@a39f721a15ed34ccbc85706e6e8ae8572c9ca9c6 # v1.2.0
        with:
          aqua_version: v1.25.0
      - run: jsonnet --version
      - run: |
          while read -r file; do
            jsonnet -o "${file%net}" "$file"
          done < <(git ls-files | grep -E ".jsonnet$")
          git add .
          if ! git diff --cached --exit-code; then
            echo "Please run jsonnet" >&2
            echo "::error title=Please run jsonnet::"
            exit 1
          fi
